# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tradepb_pb2 as tradepb__pb2


class TradeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddTrade = channel.unary_unary(
        '/trade.TradeService/AddTrade',
        request_serializer=tradepb__pb2.AddTradeRequest.SerializeToString,
        response_deserializer=tradepb__pb2.AddTradeResponse.FromString,
        )
    self.DeleteTrade = channel.unary_unary(
        '/trade.TradeService/DeleteTrade',
        request_serializer=tradepb__pb2.DeleteTradeRequest.SerializeToString,
        response_deserializer=tradepb__pb2.DeleteTradeResponse.FromString,
        )
    self.DeleteTrades = channel.unary_unary(
        '/trade.TradeService/DeleteTrades',
        request_serializer=tradepb__pb2.DeleteTradesRequest.SerializeToString,
        response_deserializer=tradepb__pb2.DeleteTradesResponse.FromString,
        )
    self.DeleteAllTrades = channel.unary_unary(
        '/trade.TradeService/DeleteAllTrades',
        request_serializer=tradepb__pb2.DeleteAllTradesRequest.SerializeToString,
        response_deserializer=tradepb__pb2.DeleteAllTradesResponse.FromString,
        )
    self.UpdateTrade = channel.unary_unary(
        '/trade.TradeService/UpdateTrade',
        request_serializer=tradepb__pb2.UpdateTradeRequest.SerializeToString,
        response_deserializer=tradepb__pb2.UpdateTradeResponse.FromString,
        )
    self.GetTrade = channel.unary_unary(
        '/trade.TradeService/GetTrade',
        request_serializer=tradepb__pb2.GetTradeRequest.SerializeToString,
        response_deserializer=tradepb__pb2.GetTradeResponse.FromString,
        )
    self.GetTradesByMarket = channel.unary_stream(
        '/trade.TradeService/GetTradesByMarket',
        request_serializer=tradepb__pb2.GetTradesByMarketRequest.SerializeToString,
        response_deserializer=tradepb__pb2.GetTradesByMarketResponse.FromString,
        )
    self.GetTradesByDateRange = channel.unary_stream(
        '/trade.TradeService/GetTradesByDateRange',
        request_serializer=tradepb__pb2.GetTradesByDateRangeRequest.SerializeToString,
        response_deserializer=tradepb__pb2.GetTradesByDateRangeResponse.FromString,
        )
    self.GetAllTrades = channel.unary_stream(
        '/trade.TradeService/GetAllTrades',
        request_serializer=tradepb__pb2.GetAllTradesRequest.SerializeToString,
        response_deserializer=tradepb__pb2.GetAllTradesResponse.FromString,
        )
    self.Export = channel.stream_unary(
        '/trade.TradeService/Export',
        request_serializer=tradepb__pb2.ExportRequest.SerializeToString,
        response_deserializer=tradepb__pb2.ExportResponse.FromString,
        )
    self.Import = channel.stream_unary(
        '/trade.TradeService/Import',
        request_serializer=tradepb__pb2.ImportRequest.SerializeToString,
        response_deserializer=tradepb__pb2.ImportResponse.FromString,
        )
    self.TotalBalance = channel.unary_unary(
        '/trade.TradeService/TotalBalance',
        request_serializer=tradepb__pb2.TotalBalanceRequest.SerializeToString,
        response_deserializer=tradepb__pb2.TotalBalanceResponse.FromString,
        )


class TradeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTrades(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAllTrades(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTradesByMarket(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTradesByDateRange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllTrades(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Export(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Import(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TotalBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TradeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddTrade': grpc.unary_unary_rpc_method_handler(
          servicer.AddTrade,
          request_deserializer=tradepb__pb2.AddTradeRequest.FromString,
          response_serializer=tradepb__pb2.AddTradeResponse.SerializeToString,
      ),
      'DeleteTrade': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTrade,
          request_deserializer=tradepb__pb2.DeleteTradeRequest.FromString,
          response_serializer=tradepb__pb2.DeleteTradeResponse.SerializeToString,
      ),
      'DeleteTrades': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTrades,
          request_deserializer=tradepb__pb2.DeleteTradesRequest.FromString,
          response_serializer=tradepb__pb2.DeleteTradesResponse.SerializeToString,
      ),
      'DeleteAllTrades': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAllTrades,
          request_deserializer=tradepb__pb2.DeleteAllTradesRequest.FromString,
          response_serializer=tradepb__pb2.DeleteAllTradesResponse.SerializeToString,
      ),
      'UpdateTrade': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateTrade,
          request_deserializer=tradepb__pb2.UpdateTradeRequest.FromString,
          response_serializer=tradepb__pb2.UpdateTradeResponse.SerializeToString,
      ),
      'GetTrade': grpc.unary_unary_rpc_method_handler(
          servicer.GetTrade,
          request_deserializer=tradepb__pb2.GetTradeRequest.FromString,
          response_serializer=tradepb__pb2.GetTradeResponse.SerializeToString,
      ),
      'GetTradesByMarket': grpc.unary_stream_rpc_method_handler(
          servicer.GetTradesByMarket,
          request_deserializer=tradepb__pb2.GetTradesByMarketRequest.FromString,
          response_serializer=tradepb__pb2.GetTradesByMarketResponse.SerializeToString,
      ),
      'GetTradesByDateRange': grpc.unary_stream_rpc_method_handler(
          servicer.GetTradesByDateRange,
          request_deserializer=tradepb__pb2.GetTradesByDateRangeRequest.FromString,
          response_serializer=tradepb__pb2.GetTradesByDateRangeResponse.SerializeToString,
      ),
      'GetAllTrades': grpc.unary_stream_rpc_method_handler(
          servicer.GetAllTrades,
          request_deserializer=tradepb__pb2.GetAllTradesRequest.FromString,
          response_serializer=tradepb__pb2.GetAllTradesResponse.SerializeToString,
      ),
      'Export': grpc.stream_unary_rpc_method_handler(
          servicer.Export,
          request_deserializer=tradepb__pb2.ExportRequest.FromString,
          response_serializer=tradepb__pb2.ExportResponse.SerializeToString,
      ),
      'Import': grpc.stream_unary_rpc_method_handler(
          servicer.Import,
          request_deserializer=tradepb__pb2.ImportRequest.FromString,
          response_serializer=tradepb__pb2.ImportResponse.SerializeToString,
      ),
      'TotalBalance': grpc.unary_unary_rpc_method_handler(
          servicer.TotalBalance,
          request_deserializer=tradepb__pb2.TotalBalanceRequest.FromString,
          response_serializer=tradepb__pb2.TotalBalanceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'trade.TradeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
